### PR TITLE
Track daily max request limit using response header

### PR DESCRIPTION
**Pull request by raman325**

### CODE REVIEW

**Comment by lymanepp** [comment]
Thanks for cleaning up some of my changes. I'm done reviewing.

**Comment by lymanepp** [comment]
Fyi, I left a few comments on this PR that weren't addressed--one of which is a bug.

**Comment by raman325** [comment]
where? I didn't see any comments

**Comment by lymanepp** [comment]
> where did you leave the comments? I didn't see any here

I submitted https://github.com/raman325/pytomorrowio/pull/9 to address my comments.

**Pull request merged**
